version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-backend-image
    container_name: fastapi-container 
    restart: unless-stopped
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./app:/app
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file: 
    - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - 6000:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo: